packages:
- apps/*
- libs/*
- libs/infra/*
- libs/shared/*
- packages/*

onlyBuiltDependencies:
- '@nestjs/core'
- '@scarf/scarf'
- '@swc/core'
- '@tailwindcss/oxide'
- argon2
- esbuild
- nestjs-pino
- sharp
